### ISSUE TITLE
App Store clone

### ISSUE THREAD

**Issue by QuetzalPretzel** [JakeShelley1/BlockNinja#1]
I'm sorry to report that your app has been cloned :-(

See here: https://itunes.apple.com/us/app/ninja-thrower/id972399079?mt=8

He's a serial cloner, see here: https://itunes.apple.com/us/developer/daniel-dugan/id860196910 all these are clones, e.g.. "Asteroid Evaders" = "Space Evaders".  He trawls GitHub for apps to steal.

Good news, you can get his app pulled by contacting Apple Legal here:

http://www.apple.com/legal/internet-services/itunes/appstorenotices/

Let me know if you need any advice on submitting the claim, it helps to include your app id in the text and add that you icon has been infringed and even the name has been unaltered in the game/screenshots (don't be afraid to write lots even though the text entry box is tiny).

**Comment by JakeShelley1** [comment]
That's unbelievable! Thank you so much for letting me know! Just submitted the claim, hopefully it gets resolved shortly.

Is there any sort of license I should add that would make it more clear how my code can be used? I had intended for this to be a resource for anyone who was interested in programming in Swift but obviously not for them to copy everything (not that anything would have stopped this guy from doing what he did).

UPDATE: The app has been taken down

**Comment by QuetzalPretzel** [comment]
Hi Jake,

You are welcome.  That is good news and all before I could get back to you.  You might want to use the Mozilla Public Licence in future, it is more restrictive.  You could state in your readme that the code is released for educational purposes and you will not accept clones being posted to the App Store.
